# File: deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebcd-deployment
  labels:
    app: sampleweb
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleweb
  template:
    metadata:
      labels:
        app: sampleweb
    spec:
      containers:
      - name: samplewebcontainer
        image: ajinkya1107/sampleweb
        ports:
        - containerPort: 8000
