name: .Net application

on:
  push:
    branches:
      master
  workflow_dispatch:

jobs:
    build_and_test :
        runs-on: windows-latest 
            steps:
              - name: Checkout Repo
                uses: actions/checkout@v4.1.1

              - name: Build dotnet code
                working-directory: ./dotnet
                run: dotnet build --configuration Release

              - name: Test dotnet code
                working-directory: ./dotnet
                run: dotnet test --configuration Release

              - name: dotnet publish
                working-directory: ./dotnet
                run: |
                  dotnet publish -c Release -o ./myapp

              - name: Upload artifacts
                uses: actions/upload-artifact@v4.3.1
                with: 
                  name: my-artifacts
                  path: ./dotnet/myapp
       
    deploy:
 

        needs: build_and_test

            steps:
              - name: Checkout repository
                uses: actions/checkout@v3

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

              - name: Log in to Docker Hub
                run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

              - name: Build and push Docker image
                run: |
                  docker build -t ajinkya1107/sampleweb:latest .
                  docker push ajinkya1107/sampleweb:latest
